import Head from 'next/head'
import React, { useState, useEffect } from 'react';
import axios from "axios";
import Search from '../components/Search';
import ImageContainer from "./ImageContainer"


export default function Home() {
  const [data, setData] = useState([]);
  const [query, setQuery] = useState("random");
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(true);

  const client_id = "JFkRBsfjElKsPA7MwxDuoi3whaqw0SmQFgJH4JUt_0Y";
  const fetchUrl = `https://api.unsplash.com/search/photos?client_id=${client_id}&query=${query}&page=${page}`;




  const fetchImages = () => {
    axios
      .get(fetchUrl, { headers: {}, })
      .then((response) => {
        setData([...data, ...response.data.results]);
      })
      .catch((error) => {
        console.log(error);
      });
    setPage(page + 1);
  };

  
  const searchImages = (e) => {
    if (e.keyCode === 13) {
      setQuery(e.target.value);
      setData([]);
    }
  };
  useEffect(() => {
    fetchImages();
  }, [query]);

 


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search searchImages={searchImages} fetchImages={fetchImages} />

      <ImageContainer dataaa={data} fetchImages={fetchImages} hasMore={hasMore} />




    </div>
  )
}
